### ISSUE TITLE
The file name is changed after the file is downloaded. 

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#138]
下载源文件后，下载文件名不一致
![image](https://user-images.githubusercontent.com/95004531/210468464-c6670a81-60bc-46de-83b7-329460148c01.png)

**Comment by MapleWithoutWords** [comment]
resolve effect drawing:
![image](https://user-images.githubusercontent.com/38368335/222638973-ff35eadd-6feb-436d-b843-894a5352afef.png)
