### ISSUE TITLE
Remove search criteria "source" from task list

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#152]
手动创建的Job，任务列表去掉搜索条件“来源”
![image](https://user-images.githubusercontent.com/95004531/210506401-c5cb4f15-1350-4c7a-ab3f-eb5ec940f429.png)

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by kogel-net** [comment]
#291
