### ISSUE TITLE
When the CRON expression is reopened, the data should reset

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#154]
创建Job，运行策略选择CRON表达式，创建成功。再次创建Job，运行策略选择CRON表达式，打开CRON表达式弹窗，数据未重置，仍保留上次选择的数据
![image](https://user-images.githubusercontent.com/95004531/210520495-78b62235-f845-4231-9e50-ad235aa0185c.png)

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by kogel-net** [comment]
#291
