### ISSUE TITLE
The Job in the disabled state is still running

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#156]
禁用状态的Job，仍在运行
![image](https://user-images.githubusercontent.com/95004531/210539301-613f47ad-59ca-48e3-9dd5-fabd95496b86.png)

![image](https://user-images.githubusercontent.com/95004531/210539282-6ff96868-5302-40b5-80a6-ef4cf3e1c1c6.png)

**Comment by wzh425** [comment]
请不要用每秒执行的Job测试
