### ISSUE TITLE
The source file version does not match the UI

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#176]
源文件版本仅显示一行，超过一行显示展开/收起按钮。
实际结果：
![image](https://user-images.githubusercontent.com/95004531/211289510-2ec425a1-59a8-48ec-8ebc-0d6183f1ddbd.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/211289564-52644ba7-55a3-4bd7-981b-520512d11625.png)

**Comment by kogel-net** [comment]
#211 Resolve hidden display button

**Comment by wzh425** [comment]
![企业微信截图_16777262193585](https://user-images.githubusercontent.com/13762077/222320375-ce22095c-90c4-406d-b834-f235e40373ea.png)
请检查ui效果

**Comment by LazyEar0** [comment]
此问题仍存在
