### ISSUE TITLE
Enter the Project team and select the first project in the project drop-down box by default

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#226]
进入项目团队，默认选中项目下拉框中第一个项目
![image](https://user-images.githubusercontent.com/95004531/223032726-71e43fa5-fd80-40de-acbf-f68e98b40075.png)

**Comment by wzh425** [comment]
Wait for the repair of masa blazer component library

**Comment by zyz** [comment]
#258
