### ISSUE TITLE
Job list, mouse over lead avatar, tooltips do not display lead nickname

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#237]
Job列表，鼠标移至负责人头像上，tooltips不显示负责人昵称
![image](https://user-images.githubusercontent.com/95004531/224244693-97878302-0947-48f6-9cf4-e017b7343e9d.png)

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by zyz** [comment]
#258 Fix:Job list, mouse over lead avatar, tooltips do not display lead nickname.
