### ISSUE TITLE
The text in the source file list Tab should get the project name and be case sensitive

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#242]
源文件列表 Tab中的文本应获取项目名称，区分大小写。现全部都是大写
![image](https://user-images.githubusercontent.com/95004531/225191333-23bd2663-5d16-4dc6-94f3-39724fe82070.png)

**Comment by zyz** [comment]
#249 Fix datetimerangepicker style modify, datetime displayed in one line.
