### ISSUE TITLE
When the time selector is selected, it should be displayed in one line

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#243]
时间选择器选中后，应在一行显示
![image](https://user-images.githubusercontent.com/95004531/225191723-a03aa083-6255-4199-90a6-ad5085294dec.png)

**Comment by zyz** [comment]
#249 Fix datetimerangepicker style modify, datetime displayed in one line.

**Comment by LazyEar0** [comment]
样式根据设计稿调整
实际结果：
![image](https://user-images.githubusercontent.com/95004531/225795123-fc2b7454-fb68-491b-9ca5-b5b85ef71559.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/225795341-c70f7439-adbe-4b93-8340-8ff8a79955e3.png)

**Comment by zyz** [comment]
#251 Change the Chinese datetime format
