### ISSUE TITLE
When a Job fails to run, an Alert is turned on. The alert will automatically resume processing the second time it is checked.

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#303]
Job运行失败开启告警，Alert第二次检查时，会自动恢复处理。
![image](https://user-images.githubusercontent.com/95004531/229699408-bb43d58f-d792-4403-9534-8519f983dd23.png)

**Comment by wzh425** [comment]
如果下次检查没有满足触发条件就会自动恢复
