### ISSUE TITLE
job- Alarm rule, help button overlaps with input field

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#307]
job-告警规则，帮助按钮与输入框重叠
![image](https://user-images.githubusercontent.com/95004531/230354425-dd741f10-145a-4181-bf4a-ca3eeb3b6e1f.png)

**Comment by LazyEar0** [comment]
沉默周期帮助按钮和输入框的间距调整一下
![image](https://user-images.githubusercontent.com/95004531/230815403-4b536d07-0c79-496f-af93-21bfe062a604.png)

**Comment by zyz** [comment]
#332
