### ISSUE TITLE
In the source file management, the case of the project name should be displayed according to the case of the actual project name in the PM

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#310]
源文件管理中，项目名称的大小写应根据PM中实际项目名称的大小写显示，目前自定首字母大写。
![image](https://user-images.githubusercontent.com/95004531/230527587-6a81f9ba-4d49-4fd3-adbb-413928d784f4.png)

**Comment by zyz** [comment]
#332
