### ISSUE TITLE
Looking at the log of the task, after jumping to TSC, you should enter the query expression in the search box of the log

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#312]
查看任务的日志，跳转至TSC后，应在日志的搜索框内带入查询表达式
![image](https://user-images.githubusercontent.com/95004531/230529601-6aae447c-fa2a-4d38-8aa9-5af4492f961d.png)

![image](https://user-images.githubusercontent.com/95004531/230529408-58937404-bdb7-4814-97d0-53a976eb8b83.png)

**Comment by wzh425** [comment]
需要tsc支持

**Comment by wzh425** [comment]
已在tsc提交pr 等待更新
