### ISSUE TITLE
Task list style adjustment

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#361]
任务列表 样式调整
![image](https://user-images.githubusercontent.com/95004531/232016899-e1477f84-52ba-4ed0-9e2c-a226d840d455.png)
![image](https://user-images.githubusercontent.com/95004531/232017052-163f6b59-bd32-42ed-8bc5-b44fbcb6b92c.png)

**Comment by MayueCif** [comment]
换StackComponent里的SDateTimeRangeToolbar
