### ISSUE TITLE
scheduler error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#378]
进入scheduler报错
![企业微信截图_16817139018036](https://user-images.githubusercontent.com/95004531/232408361-942e0a97-ca48-4de6-91e1-20028ecb7767.png)

**Comment by wzh425** [comment]
demo环境调用Masa.Contrib.StackSdks.Tsc.Service.LogService.GetMappingAsync()报错  @Qinyouzeng

**Comment by LazyEar0** [comment]
再次报错
![image](https://user-images.githubusercontent.com/95004531/232413945-8ecea8d3-1654-44d1-8624-8295a666bcba.png)
