### ISSUE TITLE
Can't get user data

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Scheduler#393]
获取不到用户数据
![image](https://user-images.githubusercontent.com/95004531/233304917-92b6e498-e835-4cac-b903-285e3d41d27d.png)

**Comment by LazyEar0** [comment]
获取不到用户数据时，显示用户system

**Comment by wzh425** [comment]
我并不认为这是一个合理化的建议

**Comment by LazyEar0** [comment]
此问题仍存在
